### ISSUE TITLE
IEに対応していない

### ISSUE THREAD

**Issue by Lunaforte** [KashEight/hytus.net#1]
職場でIEを使用しているのですが、hytus.netが上手く表示されません。

ご対応お願いいたします。

![2021-04-01_760_1617204142](https://user-images.githubusercontent.com/18228434/113169211-57b6d080-9280-11eb-9486-e7ab1cb6d638.png)

**Comment by KashEight** [comment]
職場で見ないでください.

**Comment by Lunaforte** [comment]
困ります。。。
