### ISSUE TITLE
NOT COMPATIBLE WITH INTERNET EXPLORER

### ISSUE THREAD

**Issue by Rires-Magica** [KashEight/hytus.net#2]

**Comment by KashEight** [comment]
IE IS DEAD, DO NOT USE.

**Comment by Rires-Magica** [comment]
FUCK YOU

**Comment by Rires-Magica** [comment]
![nvidia](https://user-images.githubusercontent.com/12951531/113169663-c98f1a00-9280-11eb-9840-c970dfd64a98.jpg)
